### PR TITLE
Fix get_env bug

### PR DESCRIPTION
**Pull request by juise**
Fix for https://github.com/basho/lager/issues/354

### CODE REVIEW

**Comment by mrallen1** [comment]
Yep, that's definitely a problem. Thanks for the patch. Looks like there's some kind of whitespace or indentation issue on line 240 and 242. Would you mind cleaning that up, please?

**Comment by juise** [comment]
I'm do it intentionally, I think it's makes code more visually declarative. But if you think, that is really identation issue, i'll fix it!

And I wonder, why there is no test cases for this functionality?

**Comment by mrallen1** [comment]
I would be grateful if you write some tests for this, yes.

**Comment by juise** [comment]
Sure! I've write simple unit test for get_env/2,3 and get_env_default function. But the better way will be if you or someone who understand lager internals writes integration test (common test, not unit test) for lager application run, or for boot/0 function. Unfortunately I have no free time for it.

**Comment by mrallen1** [comment]
Cool, thanks!

**Comment by macintux** [comment]
Travis is showing more test failures than I'm seeing, but definitely there's some problem with the `lager_handler_watcher` tests.

```
module 'lager_handler_watcher'
  lager_handler_watcher: reinstall_on_initial_failure_test_...[6.079 s] ok
  lager_handler_watcher: reinstall_on_runtime_failure_test_...*failed*
in function lager_handler_watcher:'-reinstall_on_runtime_failure_test_/0-fun-4-'/0 (src/lager_handler_watcher.erl, line 183)
**error:{badmatch,undefined}
```

From running the test line by line it appears that the two "blind" pops are the problem: we're no longer getting an application startup or a gen_event crash message before the crash backend message.

**Comment by mrallen1** [comment]
Yeah that was one of the failures that cropped up when we added the sink killer - I thought I had it fixed but obviously not.

**Comment by mrallen1** [comment]
I just had an epiphany that maybe the reason it "works" on master is because this fix is the root cause of the bugs I encountered before.  I.e., they crash on master because this isn't fixed.

**Comment by mrallen1** [comment]
Sorry I'm being imprecise. `lager_watcher_handler` crashes on master because this isn't fixed on master. Here it *doesn't* crash because this patch fixes the problem. So I am wondering if the code for the original test (like from 3.0.2 tag) works now.

**Comment by macintux** [comment]
That’s quite possible. Will keep digging.

**Comment by macintux** [comment]
Received independent confirmation of this; someone reported this problem with phoenix, ejabberd and lager. This patch fixed it.

I still haven't figured out what's happening to the lager start log message (wrt the failing test) but I'm confident this is the right fix. Will file another PR to address the weird whitespace issues and the failing test at a later point in time.

Since Bors won't merge this for us with a failing test, will do it manually.

:+1: 09aee4b

**Comment by mrallen1** [comment]
Yeah I got an email too.

**Pull request merged**
