### PR TITLE
Update lager 2.x for OTP 17

### PR DESCRIPTION
**Pull request by mrallen1**
Includes several test failure fixes, a Unicode bug fix and updates goldrush to release 0.1.7.

The 2.x branch is a maintenance branch intended for lager users who do not wish to use the lager 3.0 code or its API semantics.

### CODE REVIEW

**Comment by JeetKunDoug** [comment]
:+1: tested on R16 and 17. Great work folks.

**Comment by JeetKunDoug** [comment]
Let's see if BORS sees this:
:+1: f86a3e5

**Comment by slfritchie** [comment]
Is an auto-merge good now, or is there a reason for delaying?

**Comment by mrallen1** [comment]
@borshop merge

**Comment by mrallen1** [comment]
Shouldn't delete this just yet I guess due to ongoing benchmark work

**Pull request merged**
