### PR TITLE
Leverage existing lager_app:get_env wrapper for error_logger_lager_h

### PR DESCRIPTION
**Pull request by macintux**
Thanks to @zzantozz and @tonyrog for prodding us on this. We already had a compatibility function for R15 in `lager_app`; this exposes it and uses it in `error_logger_lager_h`.

Addresses #329 (RIAK-2436) and supersedes #325 (RIAK-1644).

### CODE REVIEW

**Comment by mrallen1** [comment]
:+1: 968d879

**Comment by mrallen1** [comment]
@borshop retry

**Comment by mrallen1** [comment]
@borshop retry;

**Comment by mrallen1** [comment]
:+1: 968d879

**Comment by zzantozz** [comment]
I'm happy with this approach. I originally started going this route for my PR but chose the less invasive path for #325 because that seemed to be the preference elsewhere in lager. The code looks good to me, though some tests appear to be failing, and I can't seem to see them.

I might suggest that if you're going to export `lager_app:get_env/3`, then you should update the other places in the app that use the `case ... of` construct that I used in my PR.

**Comment by macintux** [comment]
Thanks for pointing out there are other places to clean up. Will do.

**Comment by macintux** [comment]
I reviewed all invocations of `get_env` and am reasonably satisfied after adding another commit.

The builder problems have been brought to the attention of our devops team, but dialyzer passes locally.

**Comment by mrallen1** [comment]
Reran all tests locally. LGTM. Going to merge this since borshop seems broken at the moment.

**Pull request merged**
