### PR TITLE
Fix R15 compatibility

### PR DESCRIPTION
**Pull request by macintux**
Tested on my end under R15B01, the oldest Erlang I have handy. Very minor tweak.

### CODE REVIEW

**Comment by mrallen1** [comment]
I'll give this a look when I get to my system with R15 installed. Thanks @macintux

**Comment by macintux** [comment]
Thanks again to @cmeil for pointing this out.

**Comment by mrallen1** [comment]
:+1:  2f7f7b7

**Comment by macintux** [comment]
@borshop merge

**Pull request merged**
