### PR TITLE
Function for printing stacktrace in human readable form

### PR DESCRIPTION
**Pull request by habibutsu**
During development is useful to have means for printing stacktrace in human readable form.

### CODE REVIEW

**Comment by mrallen1** [comment]
Cool idea! Thank you.  I'll test this later today.

**Comment by Vagabond** [comment]
There are some related functions in error_logger_lager_h that should be looked at/used for printing stacktraces. Some of the stuff in this PR won't be safe with older Erlang releases which don't include line numbers in stacktraces (not sure we still care?).

**Comment by mrallen1** [comment]
We are going to have to look at R15 support in particular. Good reminder. Thank you @Vagabond.

**Comment by habibutsu** [comment]
@Vagabond. I don't see any related function in error_logger_lager_h, as I understand this module have function for parsing specific stacktrace from some applications like cowboy for example.

I have not thought about it, thanks. I will check working on old releases.

**Comment by mrallen1** [comment]
@habibutsu Not trying to speak for Andrew, but these functions (which are not currently exported) may be of interest: https://github.com/basho/lager/blob/master/src/error_logger_lager_h.erl#L280-L386

**Comment by habibutsu** [comment]
Yes, there's a one problem with old version - builtin function erlang:integer_to_binary/1 is not exist in R15B. Fixed it.

**Comment by habibutsu** [comment]
@mrallen1 rewrote with using *format_mfa*

**Comment by mrallen1** [comment]
Looks great. Tests and dialyzer run clean. Thanks! :+1:

**Comment by mrallen1** [comment]
@habibutsu Getting some love on Twitter. https://twitter.com/bytemeorg/status/690289716155908096

:cake:

**Pull request merged**
