### PR TITLE
Address #332: try both id and name

### PR DESCRIPTION
**Pull request by macintux**
The `stdlib` module `supervisor` reports the child name as `id` now vs `name` previously

### CODE REVIEW

**Comment by macintux** [comment]
Supersedes #333. Thanks again @kennethlakin.

**Comment by kennethlakin** [comment]
Formatting quibble: Lower down in the file, we that the second line of case assignments is indented by four spaces. This isn't how *my* editor is set up, and it's clearly how yours is either, but it *is* kinda nice.

**Comment by mrallen1** [comment]
:+1: 0961013

**Comment by mrallen1** [comment]
@borshop retry;

**Comment by mrallen1** [comment]
:+1: 0961013

**Pull request merged**
