### PR TITLE
Backport OTP 18 test fixes from 3.x branch

### PR DESCRIPTION
**Pull request by mrallen1**
See #337 (RIAK-1846)

### CODE REVIEW

**Comment by mrallen1** [comment]
@macintux Please review

**Comment by macintux** [comment]
Not sure what's going on, but 9 tests are failing under R16.

```
pr_stacktrace_test: pr_stacktrace_throw_test...*failed*
in function lager:pr_stacktrace/2
  called as pr_stacktrace([{pr_stacktrace_test,make_throw,0,
                     [{file,"test/pr_stacktrace_test.erl"},{line,8}]},
 {pr_stacktrace_test,pr_stacktrace_throw_test,0,
                     [{file,"test/pr_stacktrace_test.erl"},{line,18}]},
 {eunit_test,'-mf_wrapper/2-fun-0-',2,[{file,"eunit_test.erl"},{line,266}]},
 {eunit_test,run_testfun,1,[{file,"eunit_test.erl"},{line,65}]},
 {eunit_proc,run_test,1,[{file,"eunit_proc.erl"},{line,506}]},
 {eunit_proc,with_timeout,3,[{file,"eunit_proc.erl"},{line,331}]},
 {eunit_proc,handle_test,2,[{file,[...]},{line,...}]},
 {eunit_proc,tests_inorder,3,[{file,...},{...}]}],{throw,{test,exception}})
in call from pr_stacktrace_test:pr_stacktrace_throw_test/0 (test/pr_stacktrace_test.erl, line 21)
in call from pr_stacktrace_test:pr_stacktrace_throw_test/0
**error:undef


pr_stacktrace_test: pr_stacktrace_bad_arg_test...*failed*
in function lager:pr_stacktrace/2
  called as pr_stacktrace([{pr_stacktrace_test,bad_arg,0,
                     [{file,"test/pr_stacktrace_test.erl"},{line,14}]},
 {pr_stacktrace_test,pr_stacktrace_bad_arg_test,0,
                     [{file,"test/pr_stacktrace_test.erl"},{line,32}]},
 {eunit_test,'-mf_wrapper/2-fun-0-',2,[{file,"eunit_test.erl"},{line,266}]},
 {eunit_test,run_testfun,1,[{file,"eunit_test.erl"},{line,65}]},
 {eunit_proc,run_test,1,[{file,"eunit_proc.erl"},{line,506}]},
 {eunit_proc,with_timeout,3,[{file,"eunit_proc.erl"},{line,331}]},
 {eunit_proc,handle_test,2,[{file,[...]},{line,...}]},
 {eunit_proc,tests_inorder,3,[{file,...},{...}]}],{error,badarg})
in call from pr_stacktrace_test:pr_stacktrace_bad_arg_test/0 (test/pr_stacktrace_test.erl, line 35)
in call from pr_stacktrace_test:pr_stacktrace_bad_arg_test/0
**error:undef


pr_stacktrace_test: pr_stacktrace_bad_arity_test...*failed*
in function lager:pr_stacktrace/2
  called as pr_stacktrace([{lists,concat,[[],[]],[]},
 {pr_stacktrace_test,pr_stacktrace_bad_arity_test,0,
                     [{file,"test/pr_stacktrace_test.erl"},{line,46}]},
 {eunit_test,'-mf_wrapper/2-fun-0-',2,[{file,"eunit_test.erl"},{line,266}]},
 {eunit_test,run_testfun,1,[{file,"eunit_test.erl"},{line,65}]},
 {eunit_proc,run_test,1,[{file,"eunit_proc.erl"},{line,506}]},
 {eunit_proc,with_timeout,3,[{file,"eunit_proc.erl"},{line,331}]},
 {eunit_proc,handle_test,2,[{file,[...]},{line,...}]},
 {eunit_proc,tests_inorder,3,[{file,...},{...}]}],{error,undef})
in call from pr_stacktrace_test:pr_stacktrace_bad_arity_test/0 (test/pr_stacktrace_test.erl, line 49)
in call from pr_stacktrace_test:pr_stacktrace_bad_arity_test/0
**error:undef


09:51:53.918 [info] Application lager started on node nonode@nohost
lager_rotate: rotate_test_ (Rotate single file)...*failed*
in function lager:log/5
  called as log(sink_event,error,<0.12692.0>,"Sink test message 1",[])
in call from lager_rotate:'-rotate_test_/0-fun-2-'/0 (test/lager_rotate.erl, line 47)
**error:undef


lager_rotate: rotate_test_ (Rotate sink)...*failed*
in function lager:log/5
  called as log(sink_event,error,<0.12718.0>,"Sink test message 1",[])
in call from lager_rotate:'-rotate_test_/0-fun-3-'/0 (test/lager_rotate.erl, line 74)
**error:undef


lager_rotate: rotate_test_ (Rotate all)...*failed*
in function lager:log/5
  called as log(sink_event,error,<0.12744.0>,"Sink test message 1",[])
in call from lager_rotate:'-rotate_test_/0-fun-4-'/0 (test/lager_rotate.erl, line 100)
**error:undef


lager_manager_killer_test: overload_test_ (module 'lager_manager_killer_test')...*failed*
in function lager_manager_killer_test:'-confirm_manager_exit/2-fun-0-'/0 (test/lager_manager_killer_test.erl, line 63)
in call from lager_manager_killer_test:'-overload_test_/0-fun-4-'/0 (test/lager_manager_killer_test.erl, line 28)
**error:{assertion_failed,[{module,lager_manager_killer_test},
                   {line,63},
                   {expression,"false"},
                   {expected,true},
                   {value,false}]}



=INFO REPORT==== 30-Mar-2016::09:52:16 ===
    application: lager
    exited: stopped
    type: temporary

=INFO REPORT==== 30-Mar-2016::09:52:16 ===
    application: goldrush
    exited: stopped
    type: temporary
lager_handler_watcher: reinstall_on_initial_failure_test_...*failed*
in function lager_handler_watcher:'-reinstall_on_initial_failure_test_/0-fun-0-'/1 (src/lager_handler_watcher.erl, line 128)
in call from lager_handler_watcher:'-reinstall_on_initial_failure_test_/0-fun-5-'/0 (src/lager_handler_watcher.erl, line 128)
**error:{assertEqual_failed,[{module,lager_handler_watcher},
                     {line,128},
                     {expression,"lager_test_backend : count ( )"},
                     {expected,1},
                     {value,{error,bad_module}}]}


compress_pr_record_test: nested_record_test (module 'compress_pr_record_test')...*failed*
in function lager:pr/3
  called as pr({a,"Notice me senpai",undefined,undefined,undefined,undefined,undefined,
   undefined},compress_pr_record_test,[compress])
in call from compress_pr_record_test:nested_record_test/0 (test/compress_pr_record_test.erl, line 14)
in call from compress_pr_record_test:nested_record_test/0
**error:undef


=======================================================
  Failed: 9.  Skipped: 0.  Passed: 198.
```

**Comment by macintux** [comment]
Apparently removing deps and rebuilding wasn't enough, had to do a distclean.

**Comment by macintux** [comment]
:+1:

**Pull request merged**
