### PR TITLE
Add abbreviated severity 'sev' available to formatter

### PR DESCRIPTION
**Pull request by saleyn**

### CODE REVIEW

**Comment by mrallen1** [comment]
Could you help me understand the intention of this change?

**Comment by saleyn** [comment]
The intention is to be able to have an option of more succinct aligned log levels in the form:
```
{lager_default_formatter,
                        [time, " [",sev,"] ", message, " [", module, ":", line, "]\n"]}]}
```
That would produce:
```
10:12:00 [W] Test warnings [some_module:123]
```

**Comment by Vagabond** [comment]
This looks fine to me. If all the tests pass and look good I don't have a problem with this landing.

**Comment by saleyn** [comment]
All the tests pass except for two, which don't pass even without applying my patch, so I believe it's benign.

**Comment by mrallen1** [comment]
Just committed d6cb3bf on intg and all the tests pass. Thanks.

**Pull request merged**
